version: 2
updates:
   - package-ecosystem: npm
     directory: /
     schedule:
        interval: monthly
     cooldown:
        default-days: 7
     groups:
        actions:
           patterns:
              - '*'
   - package-ecosystem: github-actions
     directory: .github/workflows
     schedule:
        interval: monthly
     cooldown:
        default-days: 7
     groups:
        actions:
           patterns:
              - '*'
