name: 'Azure Kubernetes set context'
description: 'Sets the kubeconfig on the machine to communicate with the Azure Kubernetes cluster. Github.com/Azure/Actions'
inputs: 
  creds:
    description: 'Azure credentials i.e. output of `az ad sp create-for-rbac --sdk-auth`'
    required: true
    default: ''
  resource-group:
    description: 'Resource Group Name'
    required: false
    default: ''
  cluster-name:
    description: 'AKS Cluster Name'
    required: false
    default: ''  
  subscription-id:
    description: 'Subscription ID'
    required: false
    default: ''
branding:
  color: 'green' # optional, decorates the entry in the GitHub Marketplace
runs:
  using: 'node12'
  main: 'lib/login.js'
