name: 'Azure Kubernetes set context'
description: 'Sets the kubeconfig on the machine to communicate with the Azure Kubernetes cluster'
inputs: 
  creds:
    description: 'Azure credentials i.e. output of `az ad sp create-for-rbac --sdk-auth`'
    required: true
    default: ''
  resource-group:
    description: 'Resource Group Name'
    required: false
    default: ''
  cluster-name:
    description: 'AKS Cluster Name'
    required: false
    default: ''
  use-admin-role:
    description: 'Gets the accessProfile for the clusterAdmin role of the managed cluster if set as true.If set to false, it gets the access profile for the clusterUser role'
    required: false
    default: true
branding:
  color: 'green' # optional, decorates the entry in the GitHub Marketplace
runs:
  using: 'node12'
  main: 'lib/login.js'
