name: "Azure Kubernetes set context"
description: "Sets the kubeconfig on the machine to communicate with the Azure Kubernetes cluster."
# Azure/login must be run before this action
inputs:
  resource-group:
    description: "Resource Group Name"
    required: true
    default: ""
  cluster-name:
    description: "AKS Cluster Name"
    required: true
    default: ""
branding:
  color: "green"
runs:
  using: "node12"
  main: "lib/run.js"
