name: Feature Request
description: File a Feature Request form, we will respond to this thread with any questions.
title: 'Feature Request: '
labels: ['Feature']
assignees: '@Azure/aks-atlanta'
body:
   - type: input
     id: feature request
     attributes:
        label: feature request
        description: also tell us the example functionality and links to relevant docs
     validations:
        required: true
   - type: input
     id: runner
     attributes:
        label: runner
        description: what runner are you using?
        placeholder: mention the runner info (self-hosted, operating system)
     validations:
        required: true
